on: [push, pull_request]
name: Test
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        run: go test -v ./...
